### ISSUE TITLE
请问支持多个用户推送与所有用户推送吗?

### ISSUE THREAD

**Issue by zhangya4548** [cncal/getui#2]
请问支持多个用户推送与所有用户推送吗?

**Comment by cncal** [comment]
你好，对所有用户推送现已支持（pushMessageToApp），对多个用户（即用户列表）的推送将在下个版本v0.0.2中支持。v0.0.2今天已开发完成，周末将进行测试和对Readme.md的更新，会在周日晚些时候release，谢谢支持。
