### ISSUE TITLE
无法设置 通知 的logo

### ISSUE THREAD

**Issue by kmlidc** [cncal/getui#6]
可否增加
$template->set_logo("");                       //通知栏logo
$template->set_logoURL("");  //通知栏logo链接

/vendor/cncal/getui/src/sdk/igetui/template/GetuiTemplate.php 第136行增加
谢谢

**Comment by cncal** [comment]
不好意思，最近在赶公司项目的进度，Issues 和 PR 也没有时间处理。我会在 6.18 之前 enhance 这个项目。对给你带来的影响表示抱歉。

**Comment by cncal** [comment]
[新版本](https://github.com/cncal/getui/releases/tag/v0.1.2)已发布。
