### ISSUE TITLE
请问能否根据别名进行推送

### ISSUE THREAD

**Issue by zzdylan** [cncal/getui#8]
看类库文档上没有说明关于别名的操作，请问能否根据别名进行推送？

**Comment by cncal** [comment]
不好意思，现在才回复你。这个版本的 package 不支持对别名的操作以及根据别名进行推送，不好意思。最近公司的开发工也比较多，所以暂时还有更新版本的时间。

**Comment by zzdylan** [comment]
好的 谢谢
